'use strict';

// node-pty bundles winpty (the legacy, pre-ConPTY Windows backend). Its gyp
// build computes a version header at configure time by shelling out to two
// batch files (GetCommitHash.bat / UpdateGenVersion.bat) via gyp's `<!()`
// command expansion. Modern gyp spawns those with a cwd that breaks the
// relative `cd shared && ...bat` calls, failing the whole build — even though
// VEShell only ever uses ConPTY at runtime.
//
// This makes winpty's version stamping fully static: pre-generate GenVersion.h
// and replace the dynamic batch invocations in winpty.gyp with literals. No
// behavioral change to the produced binary. Idempotent; safe to re-run.

const fs = require('fs');
const path = require('path');

const winptyRoot = path.join(
  __dirname, '..', 'node_modules', 'node-pty', 'deps', 'winpty'
);
const gypFile = path.join(winptyRoot, 'src', 'winpty.gyp');

if (!fs.existsSync(gypFile)) {
  console.log('patch-winpty: winpty.gyp not found, skipping.');
  process.exit(0);
}

// 1. Pre-generate src/gen/GenVersion.h (what UpdateGenVersion.bat would write).
let version = '0.0.0';
try {
  version = fs.readFileSync(path.join(winptyRoot, 'VERSION.txt'), 'utf8').trim() || version;
} catch (_) { /* use fallback */ }

const genDir = path.join(winptyRoot, 'src', 'gen');
fs.mkdirSync(genDir, { recursive: true });
const genHeader =
  `// AUTO-GENERATED by scripts/patch-winpty.js\n` +
  `const char GenVersion_Version[] = "${version}";\n` +
  `const char GenVersion_Commit[] = "none";\n`;
fs.writeFileSync(path.join(genDir, 'GenVersion.h'), genHeader, 'utf8');

// 2. Replace the two dynamic `<!()` batch calls in winpty.gyp with literals.
let gyp = fs.readFileSync(gypFile, 'utf8');
let changed = false;

const commitDynamic = `'<!(cmd /c "cd shared && GetCommitHash.bat")'`;
const commitStatic = `'none'`;
if (gyp.includes(commitDynamic)) {
  gyp = gyp.replace(commitDynamic, commitStatic);
  changed = true;
}

const genDynamic = `'<!(cmd /c "cd shared && UpdateGenVersion.bat <(WINPTY_COMMIT_HASH)")'`;
const genStatic = `'gen'`;
if (gyp.includes(genDynamic)) {
  gyp = gyp.replace(genDynamic, genStatic);
  changed = true;
}

if (changed) {
  fs.writeFileSync(gypFile, gyp, 'utf8');
  console.log(`patch-winpty: patched -> ${gypFile}`);
} else {
  console.log('patch-winpty: winpty.gyp already static.');
}
console.log(`patch-winpty: wrote GenVersion.h (version ${version}).`);
